### ISSUE TITLE
stage II

### ISSUE THREAD

**Issue by rusdevops** [Shadow-nx/list2.1#1]
- [x] 1. Стоит переименовать `addlist` в `add_list` для согласованности в именовании функций 
https://github.com/Shadow-nx/list2.1/blob/78a21bffbc59be9290fe5fe8c1c1939874e0186a/main.cpp#L60
- [x] 2. Необходимо исправить опечатку в именовании параметра функции
https://github.com/Shadow-nx/list2.1/blob/78a21bffbc59be9290fe5fe8c1c1939874e0186a/main.cpp#L48
- [x] 3. Избыточная переменная `c_str`
https://github.com/Shadow-nx/list2.1/blob/78a21bffbc59be9290fe5fe8c1c1939874e0186a/main.cpp#L67
- [x] 4. Стоит изменить проверку для улучшения читабельности кода
https://github.com/Shadow-nx/list2.1/blob/78a21bffbc59be9290fe5fe8c1c1939874e0186a/main.cpp#L14
- [x] 5. Стоит заменить способ передачи последнего аргумента
https://github.com/Shadow-nx/list2.1/blob/78a21bffbc59be9290fe5fe8c1c1939874e0186a/main.cpp#L25
- [x] 6. Какой приоритет выполнения операций в данной строчке `*numbers_count++` ?

**Comment by Shadow-nx** [comment]
all complete
